### ISSUE TITLE
On page reload user is returned to home

### ISSUE THREAD

**Issue by nmarshall23** [mariussoutier/play-angular-require-seed#28]
To reproduce, login. You will see that your url is now: http://localhost:9000/#/dashboard 

Reload the page, you will now be dumped to http://localhost:9000/#/

What is happening is that in dashboard/routes.js the resolve:userResolve isn't resolving to a valid user, so the user is taken back to /.

**Comment by nloyola** [comment]
I think that using an AngularJS constant to resolve the user in `routes.js` may lead to problems. What if a controller needs to resolve other dependencies in addition to the user?

Also, the current way it is implemented, the user is undefined on a page reload, that is why the client is rerouted to the main page.

I have pushed a commit (d66137a467d042b259f0140cec44e06c62f9e94c) to my fork with a fix for this. The main change I made was to remove the constant in `user/services.js` and replace it with a function that can be called from a **routeProvider** resolve.

Please let me know if I should submit a pull request for this change.

**Comment by nloyola** [comment]
I've been looking at the [angular-app](https://github.com/angular-app/angular-app) GitHub project. Perhaps using a [securityAuthorization](https://github.com/angular-app/angular-app/blob/master/client/src/common/security/authorization.js) service may be a better implementation?

**Comment by mariussoutier** [comment]
You just have to use `$cookies` correctly ;)
