### ISSUE TITLE
sbt dist stuck after "Done packaging"

### ISSUE THREAD

**Issue by UriShohet** [mariussoutier/play-angular-require-seed#29]
Hi,

I've downloaded the master.zip and tried to do what it says in the Readme

'sbt dist' has stuck after it wrote "Done packaging". Nothing happens. According to JVisualVM "Trireme Script Thread" is running.

I've also tried running 'sbt start -Dconfig.resource=prod.conf'. Same issue.

Do you have any idea what's wrong? Your help would be greatly appreciated.

Thanks in advance,
Uri

**Comment by UriShohet** [comment]
Update - after more than 5 minutes (!) it wrote
[info] Optimizing (standard.keepLines.keepWhitespace) CSS file: /opt/clf/diy/dev/play-angular-require-seed-master/target/web/rjs/build/stylesheets/main.css
[info] Optimizing (standard.keepLines.keepWhitespace) CSS file: /opt/clf/diy/dev/play-angular-require-seed-master/target/web/rjs/build/lib/angularjs/angular-csp.css
[info] Optimizing (standard.keepLines.keepWhitespace) CSS file: /opt/clf/diy/dev/play-angular-require-seed-master/target/web/rjs/build/lib/bootstrap/css/bootstrap.css
[info] Optimizing (standard.keepLines.keepWhitespace) CSS file: /opt/clf/diy/dev/play-angular-require-seed-master/target/web/rjs/build/lib/bootstrap/css/bootstrap-theme.min.css
[info] Optimizing (standard.keepLines.keepWhitespace) CSS file: /opt/clf/diy/dev/play-angular-require-seed-master/target/web/rjs/build/lib/bootstrap/css/bootstrap-theme.css
[info] Optimizing (standard.keepLines.keepWhitespace) CSS file: /opt/clf/diy/dev/play-angular-require-seed-master/target/web/rjs/build/lib/bootstrap/css/bootstrap.min.css
[info] 
[info] Tracing dependencies for: main
[info] Uglify2 file: /opt/clf/diy/dev/play-angular-require-seed-master/target/web/rjs/build/javascripts/main.js
...
...

and then finally started....

Uri

**Comment by mariussoutier** [comment]
Don't use Trireme, use Node.

Add to sbt:
`JsEngineKeys.engineType := JsEngineKeys.EngineType.Node`
