### ISSUE TITLE
Angular 2 Support with typescript

### ISSUE THREAD

**Issue by dhirenpratap** [mariussoutier/play-angular-require-seed#38]
First, I would like to thanks for the seed. 

But, As angular 2 has been launched last year and still in beta. Any plan for the upgrade.

**Comment by mariussoutier** [comment]
I don't think I'll upgrade this seed, I'll create a new one for Angular 2 specifically because it differs so much from Angular 1 and you have to use a different language.

**Comment by dhirenpratap** [comment]
That would be great. Looking forward to it.
